name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  debian:
    name: Debian
    runs-on: ubuntu-latest
    container: docker.io/library/debian:sid

    steps:
      - name: Install basic tools
        run: |
          apt-get update
          apt-get install -y git ca-certificates

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          apt-get install -y \
            equivs \
            curl \
            devscripts \
            lintian \
            build-essential \
            automake \
            autotools-dev \
            cmake \
            g++

      - name: Install build dependencies
        run: mk-build-deps -i -t "apt-get --yes" -r

      - name: Build package
        run: dpkg-buildpackage -b -uc -us -j$(nproc)
